package com.test.domicilios.application

import org.apache.commons.io.IOUtils
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.io.File
import java.io.FileInputStream
import java.util.stream.IntStream

internal class DeliveryServiceImplTest {

    private val deliveryRoutesFilesPath = this.javaClass.getResource("/delivery-routes-files").path
    private val expectedOutputFilesPath = this.javaClass.getResource("/expected-output-files").path
    private val actualOutputFilesPath = this.javaClass.getResource("/output-files").path
    private val deliveryService = DeliveryServiceImpl(RouterServiceImpl)

    @Test
    fun `test report files generated by the 20 drones sent`() {
        IntStream.rangeClosed(1, 20)
            .mapToObj { index -> if (index < 10) { "0$index" } else { index.toString() } }
            .map { indexStr -> File("$deliveryRoutesFilesPath/in$indexStr.txt") }
            .forEach { inputFile ->
                deliveryService.deliver(inputFile.absolutePath, 3)
                val actualOutputFile = File("$actualOutputFilesPath/" + inputFile.name.replace("in", "out"))
                val expectedOutputFile = File("$expectedOutputFilesPath/" + inputFile.name.replace("in", "out"))
                assertTrue(
                    IOUtils.contentEquals(FileInputStream(actualOutputFile), FileInputStream(expectedOutputFile)))
                actualOutputFile.delete()
            }
    }
}